dist: bionic

language: minimal

install:
  - .travis/get_zola.sh

script:
  - zola build

after_success: |
  [ $TRAVIS_BRANCH = code ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  zola build &&
  cp -R static/card public &&
  sudo pip install ghp-import &&
  ghp-import -c www.davidoniani.com -n public -b master &&
  git push -fq https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git master
