dist: bionic

language: generic

install:
  - .travis/get_zola.sh

script:
  - cd website
  - zola build
  - cp static/CNAME public/CNAME
  - cp static/favicon.ico public/favicon.ico
  - mv public/* ../
  - cd ..

deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  keep-history: false
  allow-empty-commit: true
